// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: messages/stotage_message/message.proto

package stotage_message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	driver_enum "grpc-laptop/go_protos/enums/driver_enum"
	memory_message "grpc-laptop/go_protos/messages/memory_message"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Storage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        driver_enum.Driver     `protobuf:"varint,1,opt,name=driver,proto3,enum=protos.enums.driver_enum.Driver" json:"driver,omitempty"`
	Memory        *memory_message.Memory `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Storage) Reset() {
	*x = Storage{}
	mi := &file_messages_stotage_message_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storage) ProtoMessage() {}

func (x *Storage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_stotage_message_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storage.ProtoReflect.Descriptor instead.
func (*Storage) Descriptor() ([]byte, []int) {
	return file_messages_stotage_message_message_proto_rawDescGZIP(), []int{0}
}

func (x *Storage) GetDriver() driver_enum.Driver {
	if x != nil {
		return x.Driver
	}
	return driver_enum.Driver(0)
}

func (x *Storage) GetMemory() *memory_message.Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

var File_messages_stotage_message_message_proto protoreflect.FileDescriptor

var file_messages_stotage_message_message_proto_rawDesc = string([]byte{
	0x0a, 0x26, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x73, 0x74, 0x6f, 0x74, 0x61,
	0x67, 0x65, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x73, 0x74, 0x6f, 0x74, 0x61, 0x67, 0x65,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1c, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2f,
	0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x65, 0x6e, 0x75, 0x6d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x25, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x83, 0x01,
	0x0a, 0x07, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x64, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f,
	0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x52, 0x06, 0x64, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x06, 0x6d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x6c, 0x61, 0x70, 0x74,
	0x6f, 0x70, 0x2f, 0x67, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x73, 0x74, 0x6f, 0x74, 0x61, 0x67, 0x65, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_messages_stotage_message_message_proto_rawDescOnce sync.Once
	file_messages_stotage_message_message_proto_rawDescData []byte
)

func file_messages_stotage_message_message_proto_rawDescGZIP() []byte {
	file_messages_stotage_message_message_proto_rawDescOnce.Do(func() {
		file_messages_stotage_message_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_stotage_message_message_proto_rawDesc), len(file_messages_stotage_message_message_proto_rawDesc)))
	})
	return file_messages_stotage_message_message_proto_rawDescData
}

var file_messages_stotage_message_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_messages_stotage_message_message_proto_goTypes = []any{
	(*Storage)(nil),               // 0: protos.message.stotage_message.Storage
	(driver_enum.Driver)(0),       // 1: protos.enums.driver_enum.Driver
	(*memory_message.Memory)(nil), // 2: protos.messages.memory_message.Memory
}
var file_messages_stotage_message_message_proto_depIdxs = []int32{
	1, // 0: protos.message.stotage_message.Storage.driver:type_name -> protos.enums.driver_enum.Driver
	2, // 1: protos.message.stotage_message.Storage.memory:type_name -> protos.messages.memory_message.Memory
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_messages_stotage_message_message_proto_init() }
func file_messages_stotage_message_message_proto_init() {
	if File_messages_stotage_message_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_stotage_message_message_proto_rawDesc), len(file_messages_stotage_message_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_stotage_message_message_proto_goTypes,
		DependencyIndexes: file_messages_stotage_message_message_proto_depIdxs,
		MessageInfos:      file_messages_stotage_message_message_proto_msgTypes,
	}.Build()
	File_messages_stotage_message_message_proto = out.File
	file_messages_stotage_message_message_proto_goTypes = nil
	file_messages_stotage_message_message_proto_depIdxs = nil
}
