// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: messages/filter_message/message.proto

package filter_message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	memory_message "grpc-laptop/go_protos/messages/memory_message"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxPriceUsd   float64                `protobuf:"fixed64,1,opt,name=max_price_usd,json=maxPriceUsd,proto3" json:"max_price_usd,omitempty"`
	MinCpuCores   uint32                 `protobuf:"varint,2,opt,name=min_cpu_cores,json=minCpuCores,proto3" json:"min_cpu_cores,omitempty"`
	MinCpuGhz     float64                `protobuf:"fixed64,3,opt,name=min_cpu_ghz,json=minCpuGhz,proto3" json:"min_cpu_ghz,omitempty"`
	MinRam        *memory_message.Memory `protobuf:"bytes,4,opt,name=min_ram,json=minRam,proto3" json:"min_ram,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterMessage) Reset() {
	*x = FilterMessage{}
	mi := &file_messages_filter_message_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterMessage) ProtoMessage() {}

func (x *FilterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_filter_message_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterMessage.ProtoReflect.Descriptor instead.
func (*FilterMessage) Descriptor() ([]byte, []int) {
	return file_messages_filter_message_message_proto_rawDescGZIP(), []int{0}
}

func (x *FilterMessage) GetMaxPriceUsd() float64 {
	if x != nil {
		return x.MaxPriceUsd
	}
	return 0
}

func (x *FilterMessage) GetMinCpuCores() uint32 {
	if x != nil {
		return x.MinCpuCores
	}
	return 0
}

func (x *FilterMessage) GetMinCpuGhz() float64 {
	if x != nil {
		return x.MinCpuGhz
	}
	return 0
}

func (x *FilterMessage) GetMinRam() *memory_message.Memory {
	if x != nil {
		return x.MinRam
	}
	return nil
}

var File_messages_filter_message_message_proto protoreflect.FileDescriptor

var file_messages_filter_message_message_proto_rawDesc = string([]byte{
	0x0a, 0x25, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x25, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb8,
	0x01, 0x0a, 0x0d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x22, 0x0a, 0x0d, 0x6d, 0x61, 0x78, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x75, 0x73,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x6d, 0x61, 0x78, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x55, 0x73, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x6d, 0x69, 0x6e, 0x5f, 0x63, 0x70, 0x75, 0x5f,
	0x63, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6d, 0x69, 0x6e,
	0x43, 0x70, 0x75, 0x43, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0b, 0x6d, 0x69, 0x6e, 0x5f,
	0x63, 0x70, 0x75, 0x5f, 0x67, 0x68, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6d,
	0x69, 0x6e, 0x43, 0x70, 0x75, 0x47, 0x68, 0x7a, 0x12, 0x3f, 0x0a, 0x07, 0x6d, 0x69, 0x6e, 0x5f,
	0x72, 0x61, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x6d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x52, 0x06, 0x6d, 0x69, 0x6e, 0x52, 0x61, 0x6d, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x72, 0x70,
	0x63, 0x2d, 0x6c, 0x61, 0x70, 0x74, 0x6f, 0x70, 0x2f, 0x67, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x66, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_messages_filter_message_message_proto_rawDescOnce sync.Once
	file_messages_filter_message_message_proto_rawDescData []byte
)

func file_messages_filter_message_message_proto_rawDescGZIP() []byte {
	file_messages_filter_message_message_proto_rawDescOnce.Do(func() {
		file_messages_filter_message_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_filter_message_message_proto_rawDesc), len(file_messages_filter_message_message_proto_rawDesc)))
	})
	return file_messages_filter_message_message_proto_rawDescData
}

var file_messages_filter_message_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_messages_filter_message_message_proto_goTypes = []any{
	(*FilterMessage)(nil),         // 0: protos.messages.filter_message.FilterMessage
	(*memory_message.Memory)(nil), // 1: protos.messages.memory_message.Memory
}
var file_messages_filter_message_message_proto_depIdxs = []int32{
	1, // 0: protos.messages.filter_message.FilterMessage.min_ram:type_name -> protos.messages.memory_message.Memory
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_messages_filter_message_message_proto_init() }
func file_messages_filter_message_message_proto_init() {
	if File_messages_filter_message_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_filter_message_message_proto_rawDesc), len(file_messages_filter_message_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_filter_message_message_proto_goTypes,
		DependencyIndexes: file_messages_filter_message_message_proto_depIdxs,
		MessageInfos:      file_messages_filter_message_message_proto_msgTypes,
	}.Build()
	File_messages_filter_message_message_proto = out.File
	file_messages_filter_message_message_proto_goTypes = nil
	file_messages_filter_message_message_proto_depIdxs = nil
}
