// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: enums/panel_enum/enum.proto

package panel_enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Panel int32

const (
	Panel_UNKNOWN Panel = 0
	Panel_IPS     Panel = 1
	Panel_OLED    Panel = 2
)

// Enum value maps for Panel.
var (
	Panel_name = map[int32]string{
		0: "UNKNOWN",
		1: "IPS",
		2: "OLED",
	}
	Panel_value = map[string]int32{
		"UNKNOWN": 0,
		"IPS":     1,
		"OLED":    2,
	}
)

func (x Panel) Enum() *Panel {
	p := new(Panel)
	*p = x
	return p
}

func (x Panel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Panel) Descriptor() protoreflect.EnumDescriptor {
	return file_enums_panel_enum_enum_proto_enumTypes[0].Descriptor()
}

func (Panel) Type() protoreflect.EnumType {
	return &file_enums_panel_enum_enum_proto_enumTypes[0]
}

func (x Panel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Panel.Descriptor instead.
func (Panel) EnumDescriptor() ([]byte, []int) {
	return file_enums_panel_enum_enum_proto_rawDescGZIP(), []int{0}
}

var File_enums_panel_enum_enum_proto protoreflect.FileDescriptor

var file_enums_panel_enum_enum_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2f, 0x70, 0x61, 0x6e, 0x65, 0x6c, 0x5f, 0x65, 0x6e,
	0x75, 0x6d, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x70, 0x61, 0x6e, 0x65,
	0x6c, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2a, 0x27, 0x0a, 0x05, 0x50, 0x61, 0x6e, 0x65, 0x6c, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03,
	0x49, 0x50, 0x53, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x4c, 0x45, 0x44, 0x10, 0x02, 0x42,
	0x28, 0x5a, 0x26, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x6c, 0x61, 0x70, 0x74, 0x6f, 0x70, 0x2f, 0x67,
	0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2f, 0x70,
	0x61, 0x6e, 0x65, 0x6c, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_enums_panel_enum_enum_proto_rawDescOnce sync.Once
	file_enums_panel_enum_enum_proto_rawDescData []byte
)

func file_enums_panel_enum_enum_proto_rawDescGZIP() []byte {
	file_enums_panel_enum_enum_proto_rawDescOnce.Do(func() {
		file_enums_panel_enum_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enums_panel_enum_enum_proto_rawDesc), len(file_enums_panel_enum_enum_proto_rawDesc)))
	})
	return file_enums_panel_enum_enum_proto_rawDescData
}

var file_enums_panel_enum_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enums_panel_enum_enum_proto_goTypes = []any{
	(Panel)(0), // 0: protos.enums.panel_enum.Panel
}
var file_enums_panel_enum_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enums_panel_enum_enum_proto_init() }
func file_enums_panel_enum_enum_proto_init() {
	if File_enums_panel_enum_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enums_panel_enum_enum_proto_rawDesc), len(file_enums_panel_enum_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enums_panel_enum_enum_proto_goTypes,
		DependencyIndexes: file_enums_panel_enum_enum_proto_depIdxs,
		EnumInfos:         file_enums_panel_enum_enum_proto_enumTypes,
	}.Build()
	File_enums_panel_enum_enum_proto = out.File
	file_enums_panel_enum_enum_proto_goTypes = nil
	file_enums_panel_enum_enum_proto_depIdxs = nil
}
