// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: enums/driver_enum/enum.proto

package driver_enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Driver int32

const (
	Driver_UNKNOWN Driver = 0
	Driver_HDD     Driver = 1
	Driver_SSD     Driver = 2
)

// Enum value maps for Driver.
var (
	Driver_name = map[int32]string{
		0: "UNKNOWN",
		1: "HDD",
		2: "SSD",
	}
	Driver_value = map[string]int32{
		"UNKNOWN": 0,
		"HDD":     1,
		"SSD":     2,
	}
)

func (x Driver) Enum() *Driver {
	p := new(Driver)
	*p = x
	return p
}

func (x Driver) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Driver) Descriptor() protoreflect.EnumDescriptor {
	return file_enums_driver_enum_enum_proto_enumTypes[0].Descriptor()
}

func (Driver) Type() protoreflect.EnumType {
	return &file_enums_driver_enum_enum_proto_enumTypes[0]
}

func (x Driver) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Driver.Descriptor instead.
func (Driver) EnumDescriptor() ([]byte, []int) {
	return file_enums_driver_enum_enum_proto_rawDescGZIP(), []int{0}
}

var File_enums_driver_enum_enum_proto protoreflect.FileDescriptor

var file_enums_driver_enum_enum_proto_rawDesc = string([]byte{
	0x0a, 0x1c, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2f, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x65,
	0x6e, 0x75, 0x6d, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x64, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x2a, 0x27, 0x0a, 0x06, 0x44, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x07, 0x0a, 0x03, 0x48, 0x44, 0x44, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x53, 0x44, 0x10,
	0x02, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x6c, 0x61, 0x70, 0x74, 0x6f, 0x70,
	0x2f, 0x67, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73,
	0x2f, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_enums_driver_enum_enum_proto_rawDescOnce sync.Once
	file_enums_driver_enum_enum_proto_rawDescData []byte
)

func file_enums_driver_enum_enum_proto_rawDescGZIP() []byte {
	file_enums_driver_enum_enum_proto_rawDescOnce.Do(func() {
		file_enums_driver_enum_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enums_driver_enum_enum_proto_rawDesc), len(file_enums_driver_enum_enum_proto_rawDesc)))
	})
	return file_enums_driver_enum_enum_proto_rawDescData
}

var file_enums_driver_enum_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enums_driver_enum_enum_proto_goTypes = []any{
	(Driver)(0), // 0: protos.enums.driver_enum.Driver
}
var file_enums_driver_enum_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enums_driver_enum_enum_proto_init() }
func file_enums_driver_enum_enum_proto_init() {
	if File_enums_driver_enum_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enums_driver_enum_enum_proto_rawDesc), len(file_enums_driver_enum_enum_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enums_driver_enum_enum_proto_goTypes,
		DependencyIndexes: file_enums_driver_enum_enum_proto_depIdxs,
		EnumInfos:         file_enums_driver_enum_enum_proto_enumTypes,
	}.Build()
	File_enums_driver_enum_enum_proto = out.File
	file_enums_driver_enum_enum_proto_goTypes = nil
	file_enums_driver_enum_enum_proto_depIdxs = nil
}
